src/cantine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurent.urls')),
]

src/restaurent/urls.py
from django.urls import path
from .views.menu_views import *
from .views.plat_views import *

app_name = 'restaurent'
urlpatterns = [
    # menu urls
    path('', menu_list, name='menu_list'),
    path('menu/add', menu_form, name='menu_add'),
    path('menu/update/<int:id>', menu_form, name='menu_edit'),
     path('menu/<int:id>/delete/', menu_delete, name='menu_delete'),

    # Plat Urls
    path('plat/list', plat_list, name='plat_list'),
    path('plat/add', plat_form, name='plat_add'),
    path('plat/<int:id>/update', plat_form, name='plat_edit'),
    path('plat/<int:id>/delete/', plat_delete, name='plat_delete'),

]

src/restaurent/models/menu.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel
from restaurent.models.plat import Plat

class Menu(DateTimeModel):
    plat = models.OneToOneField(Plat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Menu created on {self.creation_date}"

src/restaurent/models/plat.py
from django.db import models

class Plat(models.Model):
    name = models.CharField(max_length=255)
    summary = models.TextField()

    def __str__(self):
        return self.name

src/restaurent/forms/menu_form.py
from django import forms
from restaurent.models.menu import Menu

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

src/restaurent/forms/plat_form.py
from django import forms
from restaurent.models.plat import Plat

class PlatForm(forms.ModelForm):
    class Meta:
        model = Plat
        fields = '__all__'

src/base/views.py
from django.shortcuts import render

# Create your views here.

src/restaurent/views/menu_views.py
from django.shortcuts import render, redirect, get_object_or_404
from restaurent.models.menu import Menu
from restaurent.forms.menu_form import MenuForm


def menu_list(request):
    menus = Menu.objects.all()
    menus_count = Menu.objects.count()
    context = {
            'menus': menus,
            'menus_count': menus_count
               }
    return render(request, 'menu/menu.html', context)

def menu_form(request, id=None):
    if id:
        menu = get_object_or_404(Menu, id=id)
        form_title = "Modifier le menu"
    else:
        menu = None
        form_title = "Ajouter un menu"
    
    if request.method == 'POST':
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('restaurent:menu_list')
    else:
        form = MenuForm(instance=menu)
    
    return render(request, 'menu/menu_form.html', {'form': form, 'form_title': form_title})


def menu_delete(request, id):
    menu = get_object_or_404(Menu, id=id)
    menu.delete()
    return redirect('restaurent:plat_list')

src/restaurent/views/plat_views.py
from django.shortcuts import render, redirect, get_object_or_404
from restaurent.models.plat import Plat
from restaurent.forms.plat_form import PlatForm

def plat_list(request):
    plats = Plat.objects.all()
    plat_count = Plat.objects.count()

    context = {
            'plats': plats,
            'plat_count': plat_count,
            }
    
    return render(request, 'plat/plat.html', context)


def plat_form(request, id=None):
    if id:
        plat = get_object_or_404(Plat, id=id)
        form_title = "Modifier le plat"
    else:
        plat = None
        form_title = "Ajouter un plat"
    
    if request.method == 'POST':
        form = PlatForm(request.POST, instance=plat)
        if form.is_valid():
            form.save()
            return redirect('restaurent:plat_list')
    else:
        form = PlatForm(instance=plat)
    
    return render(request, 'plat/plat_form.html', {'form': form, 'form_title': form_title})


def plat_delete(request, id):
    plat = get_object_or_404(Plat, id=id)
    plat.delete()
    return redirect('restaurent:plat_list')

# def plat_delete(request, id):
#     plat = get_object_or_404(Plat, id=id)
#     if request.method == 'POST':
#         plat.delete()
#         return redirect('restaurent:plat_list')
    #return render(request, 'plat_confirm_delete.html', {'plat': plat})

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">

    <title>
        Ma cantine scolaire
    </title>

    <!-- Fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>

    <!-- Nucleo Icons -->
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <!-- CSS Files -->
    <link id="pagestyle" href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet"/>

    <!-- Nepcha Analytics -->
    <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>

    {% block extra_head %}{% endblock %}
</head>

<body class="g-sidenav-show bg-gray-100">
    <!-- Sidebar (sidenav) -->
    {% include 'includes/sidebar.html' %}
    

    <main class="main-content border-radius-lg">
        {% include 'includes/navbar.html' %}
        <!-- Content block to be filled by child templates -->
        {% block content %}
        {% endblock %}

        <!-- Footer -->
    {% include 'includes/footer.html' %}
    </main>

    

    <!-- Core JS Files -->
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>

    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = { damping: '0.5' };
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>

    <!-- Control Center for Material Dashboard -->
    <script src="{% static 'assets/js/material-dashboard.min.js' %}"></script>

    {% block extra_js %}{% endblock %}
</body>

</html>

src/templates/includes/footer.html
<div class="container-fluid py-4">

    <footer class="footer py-4  ">
        <div class="container-fluid">
            <div class="row align-items-center justify-content-lg-between">
                <div class="col-lg-6 mb-lg-0 mb-4">
                    <div class="copyright text-center text-sm text-muted text-lg-start">
                        © <script>
                        document.write(new Date().getFullYear())
                    </script>
                        ADA
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>

src/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">


      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
                {% if request.resolver_match.url_name == 'menu_list' %}
                    <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'restaurent:menu_add' %}">Ajouter un menu</a>
                {% elif request.resolver_match.url_name == 'plat_list' %}
                    <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'restaurent:plat_add' %}">Ajouter un plat</a>
                {% endif %}
            </li>
        </ul>
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
          <div class="input-group input-group-outline">
            <label class="form-label">Recherche par nom</label>
            <input type="text" class="form-control">
          </div>
        </div>
        <ul class="navbar-nav  justify-content-end">
          <li class="nav-item d-flex align-items-center">
            <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
          </li>
        </ul>
      </div>
    </div>
  </nav>

src/templates/includes/sidebar.html
{% load static %}

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

  <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
       aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href="../index.html"
       target="_blank">
      <img src="{% static '/assets/img/logo-ct.png' %}" class="navbar-brand-img h-100" alt="main_logo">
      <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
    </a>
  </div>


  <hr class="horizontal light mt-0 mb-2">

  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">


      <li class="nav-item">
        <a class="nav-link text-white " href="{% url 'restaurent:menu_list'  %}">

          <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <span class="material-symbols-outlined">menu_book</span>
          </div>

          <span class="nav-link-text ms-1">Menus</span>
        </a>
      </li>


      <li class="nav-item">
        <a class="nav-link text-white " href="{% url 'restaurent:plat_list'  %}">

          <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <span class="material-symbols-outlined">local_cafe</span>
          </div>

          <span class="nav-link-text ms-1">Plats</span>
        </a>
      </li>

    </ul>
  </div>

</aside>

src/templates/menu/menu.html
{% extends 'base.html' %}

{% block title %}Liste des Menus{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Liste des menus</h6>
                </div>
            </div>
            <div class="card-body px-0 pb-2">
                <div class="table-responsive p-0">
                    <table class="table align-items-center mb-0">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Plat</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for menu in menus %}
                            <tr>
                                <td>{{ menu.created_at }}</td>
                                <td>{{ menu.plat }}</td>
                                <td class="text-center">
                                    <a href="{% url 'restaurent:menu_edit' menu.id %}" class="badge badge-sm bg-gradient-success">Modifier</a>
                                    <a href="{% url 'restaurent:menu_delete' menu.id %}" class="badge badge-sm bg-gradient-danger">Supprimer</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="3" class="text-center">Aucun menu disponible</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/menu/menu_form.html
{% extends 'base.html' %}

{% block title %}Formulaire Menu{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card card-plain">
            <div class="card-header">
                <h4 class="font-weight-bolder">{{ form.instance.id|yesno:"Modifier le menu,Aujourd'hui" }}</h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                            {{ form.instance.id|yesno:"Modifier,Enregistrer" }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/plat/plat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
    <title>Liste des plats</title>
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" rel="stylesheet"/>
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet"/>
</head>

<body class="g-sidenav-show  bg-gray-200">
    {% include 'includes/sidebar.html' %}

    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg">
        <!-- Navbar -->
        {% include 'includes/navbar.html' %}
        <!-- End Navbar -->

        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card my-4">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                                <h6 class="text-white text-capitalize ps-3">Liste des plats</h6>
                            </div>
                        </div>
                        <div class="card-body px-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                        <tr>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Libelle</th>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for plat in plats %}
                                            <tr>
                                                <td>
                                                    <div class="d-flex px-2 py-1">
                                                        <div class="d-flex flex-column justify-content-center">
                                                            <h6 class="mb-0 text-sm">{{ plat.name }}</h6>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="align-middle text-center text-sm">
                                                    <a href="{% url 'restaurent:plat_edit' plat.id %}" class="badge badge-sm bg-gradient-success">Modifier</a>
                                                    <a href="{% url 'restaurent:plat_delete' plat.id %}" class="badge badge-sm bg-gradient-danger">Supprimer</a>
                                                </td>
                                            </tr>
                                        {% empty %}
                                            <tr>
                                                <td colspan="2" class="text-center">Aucun plat trouvé.</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/material-dashboard.min.js' %}"></script>
</body>

</html>

src/templates/plat/plat_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
    <title>Formulaire de plat</title>
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" rel="stylesheet"/>
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet"/>
</head>

<body class="g-sidenav-show  bg-gray-200">
    {% include 'includes/sidebar.html' %}

    <main class="main-content  mt-0">
        <section>
            <div class="page-header min-vh-100">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                            <div class="card card-plain">
                                <div class="card-header">
                                    <h4 class="font-weight-bolder">{{ form_title }}</h4>
                                </div>
                                <div class="card-body">
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="input-group input-group-outline mb-3">
                                            
                                            {{ form }}
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Enregistrer</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/material-dashboard.min.js?v=3.1.0' %}"></script>
</body>

</html>